name: Auto Pull and Composer Update on Windows

on:
  push:
    branches:
      - master

jobs:
  pull_and_update:
    runs-on:  windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull changes
        run: git pull origin master


